import Link from "next/link";
import BrandLogo from "@/components/BrandLogo";
import styles from "../../[slug]/app-page.module.css";
export const metadata = {title:"Retro Snake · Destek"};
const topics = [
  ["Kontroller ve oyun kuralları", "Yılan yatay giderken başının üstüne veya altına; dikey giderken soluna veya sağına dokunarak dönün. Her yem bölüm hedefine 1 ekler. Tek yenilemeyen engel türü taştır; taşlar ve taş duvarlar turu bitirir. 11. bölümden itibaren düz duvarlar başlar, ileri bölümlerde uzar ve çoğalır. Kenara veya kendi gövdenize çarpmak da turu bitirir."],
  ["Canlar ve antrenman", "Normal oyunda çarpışma bir can götürür. En fazla 5 can bulunur. İsteğe bağlı ödüllü reklam tamamlanıp doğrulandığında canlar 5’e tamamlanır. Antrenman can tüketmez; bölüm ilerlemesi ve kalıcı ödül kazandırmaz."],
  ["Reklamsız ve sınırsız can", "Ücretli özellik tek seferlik satın almadır; abonelik değildir ve otomatik yenilenmez. Apple ekranındaki yerel fiyat geçerlidir. Özellikler açılmadıysa aynı Apple Hesabı ile Ayarlar → Satın alımları geri yükle yolunu kullanın. Bekleyen satın alma onaylanana kadar özellikler açılmaz."],
  ["Reklam ve gizlilik", "Aktif oyun alanında reklam yoktur. Ücretsiz sürümde menü banner’ları ve isteğe bağlı tur arası ödüllü reklam bulunur. Reklam bulunabilirliği bölgeye ve bağlantıya bağlıdır. Gerektiğinde Ayarlar → Yasal ve Gizlilik → Reklam gizlilik seçenekleri üzerinden onayınızı değiştirebilirsiniz."],
  ["Takılma veya dokunma sorunu", "Oyunu güncelleyin ve yeniden açın. Sorun sürerse iPhone modeli, iOS sürümü, oyun sürümü, bölüm numarası ve sorunu tekrarlatan adımları destek e-postasına ekleyin. Uygulamayı silmek cihazdaki ilerlemeyi silebilir; sorun giderirken önce bize yazın."],
  ["Kayıtlar ve izinler", "İlerleme cihazda tutulur; bulut eşitleme ve kullanıcı hesabı yoktur. Oyun kamera, mikrofon, konum, sağlık veya bildirim izni istemez. Satın alma geri yükleme oyun ilerlemesini geri getirmez."],
];
export default function Page(){return <div className={styles.page}><nav className={styles.nav}><div className={styles.navInner}><BrandLogo/><Link className={styles.back} href="/apps/retro-snake">← Retro Snake</Link></div></nav><main className={styles.main}><section className={styles.content}><span className={styles.kicker}>Destek</span><h1>Retro Snake Destek</h1><p>Oyun, kontroller, satın alma, reklamlar ve gizlilik konusunda yardım.</p>{topics.map(([title,body])=><section key={title}><h3>{title}</h3><p>{body}</p></section>)}<h3>İade ve iletişim</h3><p>İade talepleri Apple tarafından değerlendirilir: <a href="https://reportaproblem.apple.com/">Apple üzerinden iade talebi</a>. Destek için <a href="mailto:hello@saybir.net?subject=Retro%20Snake%20Destek">hello@saybir.net</a>. Şifre veya kart bilgisi göndermeyin.</p><p><Link href="/apps/retro-snake/privacy">Gizlilik</Link> · <Link href="/apps/retro-snake/terms">Koşullar</Link> · <Link href="/apps/retro-snake/eula">Apple EULA</Link> · <Link href="/apps/retro-snake/purchases">Satın alma</Link></p></section></main></div>}
