import PageTitle from "@/components/PageTitle";
import Text from "@/components/Text";
import Link from "next/link";
import BrandLogo from "@/components/BrandLogo";
import { PreferenceControls } from "@/components/SitePreferences";
import styles from "../../[slug]/app-page.module.css";
export const metadata = {title:"Retro Snake · Destek"};
const topics = [
  ["Kontroller ve oyun kuralları", "Yılan yatay giderken başının üstüne veya altına; dikey giderken soluna veya sağına dokunarak dönün. Her yem bölüm hedefine 1 ekler. Tek yenilemeyen engel türü taştır; taşlar ve taş duvarlar turu bitirir. 11. bölümden itibaren düz duvarlar başlar, ileri bölümlerde uzar ve çoğalır. Kenara veya kendi gövdenize çarpmak da turu bitirir."],
  ["Canlar ve antrenman", "Normal oyunda çarpışma bir can götürür. En fazla 5 can bulunur. İsteğe bağlı ödüllü reklam tamamlanıp doğrulandığında canlar 5’e tamamlanır. Antrenman can tüketmez; bölüm ilerlemesi ve kalıcı ödül kazandırmaz."],
  ["Reklamsız ve sınırsız can", "Premium, aylık otomatik yenilenen aboneliktir. ABD baz fiyatı aylık 2,99 USD’dir; Apple ekranındaki yerel fiyat geçerlidir. Abonelik aktifken reklamlar kaldırılır ve sınırsız can açılır. Yenilemeyi önlemek için dönem bitiminden en az 24 saat önce Apple Hesabınızın Abonelikler bölümünden iptal edin. İptalden sonra erişim ödenen dönemin sonuna kadar sürer. Özellikler açılmadıysa aynı Apple Hesabı ile Ayarlar → Satın alımları geri yükle yolunu kullanın. Bekleyen satın alma onaylanana kadar özellikler açılmaz."],
  ["Reklam ve gizlilik", "Aktif oyun alanında reklam yoktur. Ücretsiz sürümde menü banner’ları ve isteğe bağlı tur arası ödüllü reklam bulunur. Reklam bulunabilirliği bölgeye ve bağlantıya bağlıdır. Gerektiğinde Ayarlar → Yasal ve Gizlilik → Reklam gizlilik seçenekleri üzerinden onayınızı değiştirebilirsiniz."],
  ["Takılma veya dokunma sorunu", "Oyunu güncelleyin ve yeniden açın. Sorun sürerse iPhone modeli, iOS sürümü, oyun sürümü, bölüm numarası ve sorunu tekrarlatan adımları destek e-postasına ekleyin. Uygulamayı silmek cihazdaki ilerlemeyi silebilir; sorun giderirken önce bize yazın."],
  ["Kayıtlar ve izinler", "İlerleme cihazda tutulur; bulut eşitleme ve kullanıcı hesabı yoktur. Oyun kamera, mikrofon, konum, sağlık veya bildirim izni istemez. Satın alma geri yükleme oyun ilerlemesini geri getirmez."],
];
export default function Page(){return <div className={styles.page}><nav className={styles.nav}><div className={styles.navInner}><BrandLogo/><PreferenceControls/><Link className={styles.back} href="/apps/retro-snake"><Text>{"← Retro Snake"}</Text></Link></div></nav><PageTitle name="Retro Snake" title="Destek"/><main className={styles.main}><section className={styles.content}><span className={styles.kicker}><Text>{"Destek"}</Text></span><h1><Text>{"Retro Snake Destek"}</Text></h1><p><Text>{"Oyun, kontroller, satın alma, reklamlar ve gizlilik konusunda yardım."}</Text></p>{topics.map(([title,body])=><section key={title}><h3><Text>{title}</Text></h3><p><Text>{body}</Text></p></section>)}<h3><Text>{"İade ve iletişim"}</Text></h3><p><Text>{"İade talepleri Apple tarafından değerlendirilir: "}</Text><a href="https://reportaproblem.apple.com/"><Text>{"Apple üzerinden iade talebi"}</Text></a><Text>{". Destek için "}</Text><a href="mailto:hello@saybir.net?subject=Retro%20Snake%20Destek"><Text>{"hello@saybir.net"}</Text></a><Text>{". Şifre veya kart bilgisi göndermeyin."}</Text></p><p><Link href="/apps/retro-snake/privacy"><Text>{"Gizlilik"}</Text></Link> · <Link href="/apps/retro-snake/terms"><Text>{"Koşullar"}</Text></Link> · <Link href="/apps/retro-snake/eula"><Text>{"Apple EULA"}</Text></Link> · <Link href="/apps/retro-snake/purchases"><Text>{"Satın alma"}</Text></Link></p></section></main></div>}
